### ISSUE TITLE
Android BLE Library Version?

### ISSUE THREAD

**Issue by natehurley** [fbiego/ESP32_BLE_OTA_Android#4]
Hello! First of all, I think this ESP32 BLE OTA updater is very awesome and I want to incorporate something similar into one of my ESP32 projects.

I am attempting to debug this project in Android Studio in an attempt to understand the code a bit better, but am running into the issue of not having the Android BLE library in the source folder of the application. I added the latest version of this library as a dependency with the line below

`implementation 'no.nordicsemi.android:ble:2.3.1'`

in my build.gradle file, but am still facing compiling errors (potentially due to a library version change, I'm thinking).

![image](https://user-images.githubusercontent.com/56522563/136442805-26b2ca20-0fda-4e63-a996-3fa9219486ec.png)

Would it be possible to include the library source code in the repository or inform me of the version you were using when this application was written?

Any help or suggestions will be much appreciated... Thanks in advance!

**Comment by fbiego** [comment]
the library used is https://github.com/fbiego/Android-BLE-Library which was originally from https://github.com/NordicSemiconductor/Android-BLE-Library

**Comment by natehurley** [comment]
Awesome, thanks so much for the quick reply! Everything worked immediately with your library.
