### ISSUE TITLE
How to add the dependency in android studio?

### ISSUE THREAD

**Issue by simogaspa84** [fbiego/ESP32_BLE_OTA_Android#6]
Hi ..

Great work.. 

I would like to know how to add the dependency and fix the following issues-... 

Thanks a lot 

![image](https://user-images.githubusercontent.com/12874425/157061868-7e2ddfd9-74d7-42d2-947a-5ebeae7b0774.png)

**Comment by fbiego** [comment]
try commenting out the signingconfigs

https://github.com/fbiego/ESP32_BLE_OTA_Android/blob/0c0e801451bf46c98e62ebbb52ae208347316d7e/app/build.gradle#L33

**Comment by simogaspa84** [comment]
It worked .. thanks a lot.. there is another issue on the android app... maybe you can find it on the repo issues of the esp32 code.. when I start to download the firmware via ble it says 100% completed on the app but on the esp32 side it tells incomplete and it doesn't work
